<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\SistemaReservasRestaurante.Entidades\SistemaReservasRestaurante.Entidades.csproj" />
    <ProjectReference Include="..\SistemaReservasRestaurante.BLL\SistemaReservasRestaurante.BLL.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>